- name: NBU Development -> Configure SAP HANA Protection on DB node
  hosts: sap_clients
  gather_facts: yes
  vars:
    # NetBackup Primary server
    master_server: <netbackup_primary_server>
    # NetBackup Primary server user name
    nbu_username: <netbackup_primary_server_user_name>
    # NetBackup Primary server password
    nbu_password: <netbackup_primary_server_password>
    # SAP HANA instance SYSTEM ID, for example: SSK
    sap_nbu_instance: <SID>
    # NetBackup Storage unit name
    msdp_dp_stu: <netbackup_storage_unit>
    # SAP HANA Virtual name optional
    nbu_client_vip: <sap_hana_primary_host_name>
    # SAP HANA node names (Master and worker nodes)
    # These names should be NetBackup Client names from bp.conf 
    nbu_clients:
      - client: <sap_hana_host+nbu_client-1>
      - client: <sap_hana_host+nbu_client-2>
    # SAP HANA instance SID 
    nbu_client_sid: '{{sap_nbu_instance}}'
    # SAP HANA instance number, for example: "09"
    nbu_client_ins: "<instance_id>"
    # SAP HANA hdbuserstore Key
    nbu_client_hdb: <sap_hana_user_key>
    # SAP HANA SYSTEM DB name, for example: SYSTEMDB
    nbu_client_bsl_sys: <SYSTEMDB>
    # SAP HANA tenant DB name, for example: SSK/DB1/DB2 etc
    nbu_client_bsl_ten: <tenant-DB>
    # SAP HANA user name, for example: sskadm
    sap_user: <sid>adm
    # provide the path to create the utl and backup script files
    # for example: /usr/openv/netbackup/ext/db_ext/sap/scripts/sap_oracle
    utl_script_file_path: <directory_path>
    policy_list:
      policy1:
        name: sap_sysDB_{{sap_nbu_instance}}_daily
        backupselection: "{{utl_script_file_path}}/{{sap_nbu_instance}}/NBU_{{nbu_client_sid}}_sap_backup_sys_data.sh"
        policy_temp: create_policy_sap_single_daily.j2
      policy2:
        name: sap_sysDB_{{sap_nbu_instance}}_weekly
        backupselection: "{{utl_script_file_path}}/{{sap_nbu_instance}}/NBU_{{nbu_client_sid}}_sap_backup_sys_data.sh"
        policy_temp: create_policy_sap_single_weekly.j2
      policy3:
        name: sap_sysDB_{{sap_nbu_instance}}_monthly
        backupselection: "{{utl_script_file_path}}/{{sap_nbu_instance}}/NBU_{{nbu_client_sid}}_sap_backup_sys_data.sh"
        policy_temp: create_policy_sap_single_monthly.j2
      policy4:
        name: sap_tenantDB_{{nbu_client_bsl_ten}}_daily
        backupselection: "{{utl_script_file_path}}/{{sap_nbu_instance}}/{{nbu_client_bsl_ten}}/NBU_{{nbu_client_sid}}_sap_backup_ten_data.sh"
        policy_temp: create_policy_sap_single_daily.j2
      policy5:
        name: sap_tenantDB_{{nbu_client_bsl_ten}}_weekly
        backupselection: "{{utl_script_file_path}}/{{sap_nbu_instance}}/{{nbu_client_bsl_ten}}/NBU_{{nbu_client_sid}}_sap_backup_ten_data.sh"
        policy_temp: create_policy_sap_single_weekly.j2
      policy6:
        name: sap_tenantDB_{{nbu_client_bsl_ten}}_monthly
        backupselection: "{{utl_script_file_path}}/{{sap_nbu_instance}}/{{nbu_client_bsl_ten}}/NBU_{{nbu_client_sid}}_sap_backup_ten_data.sh"
        policy_temp: create_policy_sap_single_monthly.j2

  roles:
   - netbackup-api-token-get
   - netbackup-sap-policy
   - netbackup-api-policy-sap-create








