- name: NetBackup SAP HANA -> Upload script file and add instance information for default - SYS
  template:
    src: "nbu_sap_script_system.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/NBU_{{nbu_client_sid}}_sap_backup_sys_data.sh"
    mode: '0755'

- name: NetBackup SAP HANA -> Upload script file and add instance information for default - TEN
  template:
    src: "nbu_sap_script_tenant.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/{{nbu_client_bsl_ten}}/NBU_{{nbu_client_bsl_ten}}_sap_backup_ten_data.sh"
    mode: '0755'
