- name: NetBackup SAP HANA Instance -> Check if directory exists - create directory
  file:
    path: "{{utl_script_file_path}}/{{sap_nbu_instance}}"
    state: directory
    mode: '0755'

- name: NetBackup SAP HANA tenantDB -> Check if directory exists - create directory
  file:
    path: "{{utl_script_file_path}}/{{sap_nbu_instance}}/{{nbu_client_bsl_ten}}"
    state: directory
    mode: '0755'

- name: NetBackup SAP HANA -> Upload UTL file and add backup policyname for default - <SID>
  template:
    src: "initSAP.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/initSAP_{{sap_nbu_instance}}-data.utl"
  with_items: '{{ sap_nbu_policies_daily_sys }}'

- name: NetBackup SAP HANA -> Upload UTL file and add backup policyname for default - <SID>
  template:
    src: "initSAP.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/initSAP_{{sap_nbu_instance}}-log.utl"
  with_items: '{{ sap_nbu_policies_daily_sys }}'

- name: NetBackup SAP HANA -> Upload UTL file and add backup policyname for daily backup - SYS
  template:
    src: "initSAP.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/initSAP_{{sap_nbu_instance}}-sys-data-daily.utl"
  with_items: '{{ sap_nbu_policies_daily_sys }}'

- name: NetBackup SAP HANA -> Upload UTL file and add backup policyname for weekly backup - SYS
  template:
    src: "initSAP.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/initSAP_{{sap_nbu_instance}}-sys-data-weekly.utl"
  with_items: '{{ sap_nbu_policies_weekly_sys }}'

- name: NetBackup SAP HANA -> Upload UTL file and add backup policyname for monthly backup - SYS
  template:
    src: "initSAP.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/initSAP_{{sap_nbu_instance}}-sys-data-monthly.utl"
  with_items: '{{ sap_nbu_policies_monthly_sys }}'

- name: NetBackup SAP HANA -> Upload UTL file and add backup policyname for default - TEN
  template:
    src: "initSAP.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/{{nbu_client_bsl_ten}}/initSAP_{{nbu_client_bsl_ten}}-data.utl"
  with_items: '{{ sap_nbu_policies_daily_ten }}'

- name: NetBackup SAP HANA -> Upload UTL file and add backup policyname for default - TEN
  template:
    src: "initSAP.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/{{nbu_client_bsl_ten}}/initSAP_{{nbu_client_bsl_ten}}-log.utl"
  with_items: '{{ sap_nbu_policies_daily_sys }}'

- name: NetBackup SAP HANA -> Upload UTL file and add backup policyname for daily backup - TEN
  template:
    src: "initSAP.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/{{nbu_client_bsl_ten}}/initSAP_{{nbu_client_bsl_ten}}-ten-data-daily.utl"
  with_items: '{{ sap_nbu_policies_daily_ten }}'

- name: NetBackup SAP HANA -> Upload UTL file and add backup policyname for weekly backup - TEN
  template:
    src: "initSAP.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/{{nbu_client_bsl_ten}}/initSAP_{{nbu_client_bsl_ten}}-ten-data-weekly.utl"
  with_items: '{{ sap_nbu_policies_weekly_ten }}'

- name: NetBackup SAP HANA -> Upload UTL file and add backup policyname for monthly backup - TEN
  template:
    src: "initSAP.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/{{nbu_client_bsl_ten}}/initSAP_{{nbu_client_bsl_ten}}-ten-data-monthly.utl"
  with_items: '{{ sap_nbu_policies_monthly_ten }}'

- name: NetBackup SAP HANA -> Upload script to the remote SAP HANA master host - TEN
  template:
    src: "update_sap_hana_tenant_DB_conf.j2"
    dest: "{{utl_script_file_path}}/{{sap_nbu_instance}}/update_sap_hana_{{sap_nbu_instance}}_parameters.sh"
    mode: '0755'

